from __future__ import annotations

import shutil
import subprocess
import sys
import threading
import time
from collections.abc import Iterator
from pathlib import Path

from .effects import CHUNK_BYTES, SAMPLE_RATE, pcm_spectrum_bands


class AudioCaptureError(RuntimeError):
    pass


class AudioSource:
    name = "Audio"

    def frames(self, stop: threading.Event, fps: int) -> Iterator[tuple[float, float, float]]:
        raise NotImplementedError


def default_monitor_source() -> str:
    completed = subprocess.run(["pactl", "info"], capture_output=True, text=True, timeout=4, check=False)
    if completed.returncode != 0:
        raise AudioCaptureError(completed.stderr.strip() or "pactl info failed")
    source = ""
    sink = ""
    for line in completed.stdout.splitlines():
        if line.startswith("Default Source:"):
            source = line.split(":", 1)[1].strip()
        elif line.startswith("Default Sink:"):
            sink = line.split(":", 1)[1].strip()
    if source.endswith(".monitor"):
        return source
    if sink:
        return f"{sink}.monitor"
    if source:
        return source
    raise AudioCaptureError("No default audio monitor source was found.")


class CavaSource(AudioSource):
    name = "CAVA spectrum"

    def __init__(self, state_directory: Path) -> None:
        self.config_path = state_directory / "cache" / "cava.conf"

    def frames(self, stop: threading.Event, fps: int) -> Iterator[tuple[float, float, float]]:
        source = default_monitor_source()
        self.config_path.parent.mkdir(parents=True, exist_ok=True)
        self.config_path.write_text(
            "\n".join(
                (
                    "# Generated by CaseLight.",
                    "[general]",
                    f"framerate = {max(2, min(12, fps))}",
                    "autosens = 1",
                    "sensitivity = 100",
                    "bars = 3",
                    "lower_cutoff_freq = 40",
                    "higher_cutoff_freq = 5200",
                    "sleep_timer = 0",
                    "",
                    "[input]",
                    "method = pulse",
                    f"source = {source}",
                    "",
                    "[output]",
                    "method = raw",
                    "channels = mono",
                    "mono_option = average",
                    "raw_target = /dev/stdout",
                    "data_format = ascii",
                    "ascii_max_range = 1000",
                    "bar_delimiter = 59",
                    "frame_delimiter = 10",
                    "",
                    "[smoothing]",
                    "monstercat = 1",
                    "waves = 0",
                    "noise_reduction = 55",
                    "",
                )
            ),
            encoding="utf-8",
        )
        process = subprocess.Popen(
            ["cava", "-p", str(self.config_path)],
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
        )
        try:
            if process.stdout is None:
                raise AudioCaptureError("CAVA did not provide spectrum output.")
            for line in process.stdout:
                if stop.is_set():
                    break
                values = [part.strip() for part in line.strip().split(";") if part.strip()]
                if len(values) < 3:
                    continue
                try:
                    yield tuple(max(0.0, min(1.0, float(value) / 1000.0)) for value in values[:3])  # type: ignore[misc]
                except ValueError:
                    continue
        finally:
            if process.poll() is None:
                process.terminate()


class ParecSource(AudioSource):
    name = "PulseAudio loopback"

    def frames(self, stop: threading.Event, fps: int) -> Iterator[tuple[float, float, float]]:
        command = [
            "parec",
            "--device",
            default_monitor_source(),
            "--format=s16le",
            f"--rate={SAMPLE_RATE}",
            "--channels=1",
        ]
        process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
        interval = 1.0 / max(2, min(12, fps))
        last_update = 0.0
        try:
            if process.stdout is None:
                raise AudioCaptureError("parec did not provide audio output.")
            while not stop.is_set():
                chunk = process.stdout.read(CHUNK_BYTES)
                if not chunk:
                    if process.poll() is not None:
                        break
                    continue
                now = time.monotonic()
                if now - last_update >= interval:
                    last_update = now
                    yield pcm_spectrum_bands(chunk)
        finally:
            if process.poll() is None:
                process.terminate()


class WindowsLoopbackSource(AudioSource):
    name = "Windows WASAPI loopback"

    def frames(self, stop: threading.Event, fps: int) -> Iterator[tuple[float, float, float]]:
        try:
            import numpy as np
            import soundcard as sc
        except ImportError as exc:
            raise AudioCaptureError("Windows visualization needs the 'music-windows' dependencies.") from exc
        speaker = sc.default_speaker()
        if speaker is None:
            raise AudioCaptureError("Windows has no default playback device.")
        microphone = sc.get_microphone(id=str(speaker.name), include_loopback=True)
        frames_per_read = max(1024, int(SAMPLE_RATE / max(2, min(12, fps))))
        with microphone.recorder(samplerate=SAMPLE_RATE, channels=1) as recorder:
            while not stop.is_set():
                samples = recorder.record(numframes=frames_per_read)
                pcm = (np.clip(samples[:, 0], -1.0, 1.0) * 32767.0).astype("<i2").tobytes()
                yield pcm_spectrum_bands(pcm)


def choose_audio_source(state_directory: Path) -> AudioSource:
    if sys.platform == "win32":
        return WindowsLoopbackSource()
    if shutil.which("cava") and shutil.which("pactl"):
        return CavaSource(state_directory)
    if shutil.which("parec") and shutil.which("pactl"):
        return ParecSource()
    raise AudioCaptureError("Install CAVA, or PulseAudio tools (pactl + parec), to visualize system audio.")
